# Header
menu:
  Archives: /archives
  Resources: /resources
  About: /about

# Title on top left of menu. Leave empty to use main blog title
menu_title: Home

# URL of the Home page image
index_cover: /images/homeless-2182114_1280.jpg
# Default post title
default_post_title: Untitled
default_post_icon: fa-file-text-o

# About Widget
about_widget_avatar_url: https://avatars0.githubusercontent.com/u/23219964?v=3&s=460
about_widget_text: "My name is Krystel Rae Davis and I want to encourage others to facilicate change."

# Comments. Choose one by filling up the information
comments:
  # Disqus comments
  disqus_shortname: homelessatx-com
  # Facebook comments
  facebook:
    appid:
    comment_count: 5
    comment_colorscheme: light

# Google Analytics Tracking ID
google_analytics:

# Addthis ID
addthis:

# set your own favicon
favicon:

# Social Accounts
twitter_url: https://twitter.com/krystelraedavis
twitter_handle: krystelraedavis
facebook_url: https://www.facebook.com/krystelrae
github_url: https://github.com/krsdavis
gitlab_url:
linkedin_url:
mailto: mailto:krae@homelessatx.com